spring.application.name=_app

# Conexion Supabase
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.jpqbjagkkojzxicwnyme
spring.datasource.password=GQgOypZNUL9sSqy5
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html